### ISSUE TITLE
🛠️ Project Proposal: Adding a Tic-Tac-Toe Game for Android

### ISSUE THREAD

**Issue by sayan0328** [sudo-parnab/Its-apptober#12]
### 🔖 Project Description

Play the classic game of Tic Tac Toe with a sleek, user-friendly interface, featuring both single and two-player modes. Challenge friends or the AI and enjoy endless fun!

### 🎤 Project Pitch

Adding this project to your repository provides a concise example of ViewModel, NavController, and MiniMax AI, aiding others in learning Android development and game logic.

### 📈 Expected Outcome

Adding the Tic Tac Toe game will help others learn Android development concepts, understand game logic, explore UI design with Jetpack Compose, and gain insights into implementing AI using the MiniMax algorithm.

### 📷 Screenshots

![tic-tac-toe-app](https://github.com/user-attachments/assets/2671be08-f884-44c3-b412-87e2436701d3)

### ✔️ Checklist

- [X] I have checked and confirmed no similar projects exist.
- [X] I have read and understood the [Contributing Guidelines](https://github.com/sudo-parnab/Its-algober/blob/main/CONTRIBUTING.md).
- [X] I have read and agree to the [Code of Conduct](https://github.com/sudo-parnab/Its-algober/blob/main/CODE_OF_CONDUCT.md).
- [X] I am a Hacktoberfest 2024 contributor.
- [X] I am willing to work on this issue.

**Comment by sudo-parnab** [comment]
go ahead

**Comment by sayan0328** [comment]
Ok
