### ISSUE TITLE
🛠️ Project Proposal: Task Master App for Android

### ISSUE THREAD

**Issue by sayan0328** [sudo-parnab/Its-apptober#16]
### 🔖 Project Description

Task Master is a todo list management app that allows users to organize, track, and manage their tasks efficiently. The app offers features such as adding, duplicating, editing and deleting tasks. Simplify your task management and boost productivity.

### 🎤 Project Pitch

Task Master is a todo list management app built with Kotlin, Jetpack Compose, ViewModel, LiveData, RoomDB, and NavController. It allows users to efficiently add, edit, and manage tasks, offering a seamless and responsive user experience.

### 📈 Expected Outcome

By exploring Task Master, learners can understand how to implement Jetpack Compose for UI, manage state with ViewModel and LiveData, use RoomDB for local storage, and handle app navigation through NavController in Android development.

### 📷 Screenshots

![todo-list-app](https://github.com/user-attachments/assets/559a6b0c-48e2-4ae8-b343-646e3e798562)

### ✔️ Checklist

- [X] I have checked and confirmed no similar projects exist.
- [X] I have read and understood the [Contributing Guidelines](https://github.com/sudo-parnab/Its-algober/blob/main/CONTRIBUTING.md).
- [X] I have read and agree to the [Code of Conduct](https://github.com/sudo-parnab/Its-algober/blob/main/CODE_OF_CONDUCT.md).
- [X] I am a Hacktoberfest 2024 contributor.
- [X] I am willing to work on this issue.

### 📝 Additional Notes (Optional)

This app uses CoroutineDispatcher to process addition of todo items in a different thread, thus preventing the app from crashing.

**Comment by sudo-parnab** [comment]
go ahead

**Comment by sayan0328** [comment]
Ok
